[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_BACKEND_URL = "https://wom-be-test.onrender.com"

[context.deploy-preview]
  command = "NEXT_PUBLIC_BACKEND_URL=https://wom-be-test-pr-${REVIEW_ID:?No preview backend available - REVIEW_ID is not set}.onrender.com npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"
