[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_BACKEND_URL = "https://tjuvpakk-backend.onrender.com"

[context.deploy-preview.environment]
  NEXT_PUBLIC_BACKEND_URL = "https://wom-be-test.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"
